version: '3.8'

services:
  host:
    container_name: build-host
    privileged: true
    build:
      context: .
    image: host-image
    networks:
      - build-network

  build-environment:
    container_name: build-environment
    privileged: true
    build:
      context: .
    image: build-environment-image
    networks:
      - build-network

networks:
  build-network:

