[package]
name = "cairn-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["cargo"] }
dotenv = "0.15.0"
log = "0.4.20"
regex = "1.10.2"
