name: benchmark

on:
  push:
    branches:
      - benchmark

jobs:
  benchmark:
    runs-on: self-hosted

    steps:
    - name: Tear down the previous docker container
      id: docker-status
      run: bash teardown.sh || true

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and install the cli tool
      run: cargo install --path ./cairn-cli

    - name: Start the docker containers
      run: bash init.sh -b ./host_mnt

    - name: Install pip dependencies in venv
      run: python3 -m venv venv && source venv/bin/activate && pip install -r benchmarks/requirements.txt

    - name: Run the benchmarks
      run: bash benchmarks/run.sh

    - name: Publish benchmark results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.sha }} 
        path: benchmarks/*.zip 
