name: benchmark

on:
  push:
    branches:
      - benchmark

jobs:
  benchmark:
    runs-on: self-hosted

    steps:
    - name: Tear down the previous docker container
      id: docker-status
      run: |
        bash teardown.sh || true
        rm /usr/local/bin/fsatrace || true

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and install the client
      run: cargo install --path ./fsatrace

    # - name: Start the docker containers
    #   run: bash init.sh -b $(pwd)/host_mnt
    #
    # - name: Install pip dependencies in venv
    #   run: python3 -m venv venv && source venv/bin/activate && pip install -r benchmarks/requirements.txt
    #
    # - name: Run the benchmarks
    #   run: bash benchmarks/run.sh -s 1 -e 5 -r 1
    #
    # - name: Stop the docker containers
    #   run: bash teardown.sh

    - name: Clone rattle repo
      run: |
        mkdir rattle
        git clone https://github.com/xelahalo/rattle.git ./rattle

    - name: Set up Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: 9.8.1
        cabal-version: 3.10.1.0

    - name: Run rattle benchmarks (cairn)
      run: |
        bash benchmarks/rattle-benchmark.sh
        mv rattle/vsmake.log rattle/vsmake-cairn.log

    - name: Build fsatrace
      run: |
        cargo uninstall fsatrace
        mkdir -p fsatrace-original
        git clone https://github.com/xelahalo/fsatrace.git ./fsatrace-original
        cd fsatrace-original || exit 1
        make
        ln -s $(pwd)/fsatrace /usr/local/bin/fsatrace
        cd - || exit 1

    - name: Run rattle benchmarks (fsatrace)
      run: |
        bash benchmarks/rattle-benchmark.sh
        mv rattle/vsmake.log rattle/vsmake-fsatrace.log

    - name: Publish benchmark results
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }} 
        path: |
          benchmarks/*.zip
          rattle/vsmake-cairn.log
          rattle/vsmake-fsatrace.log
