name: benchmark

on:
  push:
    branches:
      - benchmark

jobs:
  benchmark:
    runs-on: self-hosted

    steps:
    - name: Tear down the previous docker container
      id: docker-status
      run: bash teardown.sh || true

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and install the client
      run: cargo install --path ./fsatrace

    - name: Start the docker containers
      run: bash init.sh -b $(pwd)/host_mnt

    - name: Install pip dependencies in venv
      run: python3 -m venv venv && source venv/bin/activate && pip install -r benchmarks/requirements.txt

    - name: Run the benchmarks
      run: bash benchmarks/run.sh -s 1 -e 5 -r 1

    - name: Stop the docker containers
      run: bash teardown.sh

    - name: Clone rattle repo
      run: |
        mkdir rattle
        git clone https://github.com/xelahalo/rattle.git ./rattle

    - name: Set up Haskell
      uses: actions/setup-haskell@v1.1
      with:
        ghc-version: 9.8.1
        cabal-version: 3.10.1.0

    - name: Run benchmarks with rattle
      run: bash benchmarks/rattle-benchmark.sh

    - name: Publish benchmark results
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }} 
        path: |
          benchmarks/*.zip
          rattle/vsmake.log