name: benchmark

on:
  push:
    branches:
      - benchmark

jobs:
  benchmark:
    runs-on: self-hosted

    steps:
    - name: Tear down the previous docker container
      id: docker-status
      run: bash teardown.sh

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and install the app
      run: cargo install --path .

    - name: Start the docker container
      run: bash init.sh /mnt

    - name: Run stage 1 benchmarks
      run: bash benchmarks/run.sh stage_1

    - name: Publish benchmark results
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.sha }} 
        path: benchmarks/*.zip 
