name: benchmark

on:
  push:
    branches:
      - benchmark

jobs:
  benchmark:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build and install the app
      run: cargo install --path .

    - name: Check Docker Container Status
      id: docker-status
      run: |
        if docker ps -f "name=build-env" | grep -q "build-env"; then
          echo "Container build-env is running."
          echo "::set-output name=container_running::true"
        else
          echo "Container build-env is not running."
          echo "::set-output name=container_running::false"
        fi

    - name: Start the docker container
      if: steps.docker-status.outputs.container_running == 'false'
      run: bash init.sh /mnt

    - name: Run stage 1 benchmarks
      run: bash benchmarks/run.sh stage_1

    - name: Publish results
      if: success()
      run: bash benchmarks/publish.sh

